[metadata]
name = "jellybeans-light"
author = "A. Fox"
origin_url = ""


[colors]
foreground = "#100f0f"
background = "#fffcf0"
cursor_fg = "#fffcf0"
cursor_bg = "#100f0f"
cursor_border = "#100f0f"
selection_fg = "#100f0f"
selection_bg = "#dad8ce"
compose_cursor = "#100f0f"
visual_bell = "#d14d41"

ansi = [
  "#100f0f", # black
  "#d14d41", # red
  "#879a39", # green
  "#d0a215", # yellow
  "#4385be", # blue
  "#8b7ec8", # magenta/purple
  "#3aa99f", # cyan
  "#f2f0e5", # white
]

brights = [
  "#6f6e69", # bright black/subtle
  "#af3029", # bright red
  "#66800b", # bright green
  "#ad8301", # bright yellow
  "#205ea6", # bright blue
  "#5e409d", # bright magenta/purple
  "#24837b", # bright cyan
  "#fffcf0", # bright white/base
]

[colors.indexed]
16 = "#da702c" # orange_one
17 = "#ce5d97" # magenta_one
18 = "#fffdf5" # surface
19 = "#e6e4d9" # highlight_low
20 = "#b7b5ac" # muted
21 = "#cecdc3" # highlight_high

[colors.tab_bar]
background = "#f2f0e5" # overlay

active_tab.bg_color = "#fffcf0" # base
active_tab.fg_color = "#100f0f" # text

inactive_tab.bg_color = "#f2f0e5" # overlay
inactive_tab.fg_color = "#6f6e69" # subtle

inactive_tab_hover.bg_color = "#fffdf5" # surface
inactive_tab_hover.fg_color = "#100f0f" # text

new_tab.bg_color = "#f2f0e5" # overlay[metadata]
name = "dawn"
author = "User"
origin_url = ""

[colors]
foreground = "#100f0f"
background = "#fffcf0"
cursor_fg = "#fffcf0"
cursor_bg = "#100f0f"
cursor_border = "#100f0f"
selection_fg = "#100f0f"
selection_bg = "#dad8ce"
compose_cursor = "#100f0f"
visual_bell = "#d14d41"

ansi = [
  "#100f0f", # black
  "#d14d41", # red
  "#879a39", # green
  "#d0a215", # yellow
  "#4385be", # blue
  "#8b7ec8", # magenta/purple
  "#3aa99f", # cyan
  "#f2f0e5", # white
]

brights = [
  "#6f6e69", # bright black/subtle
  "#af3029", # bright red
  "#66800b", # bright green
  "#ad8301", # bright yellow
  "#205ea6", # bright blue
  "#5e409d", # bright magenta/purple
  "#24837b", # bright cyan
  "#fffcf0", # bright white/base
]

[colors.indexed]
16 = "#da702c" # orange_one
17 = "#ce5d97" # magenta_one
18 = "#fffdf5" # surface
19 = "#e6e4d9" # highlight_low
20 = "#b7b5ac" # muted
21 = "#cecdc3" # highlight_high

[colors.tab_bar]
background = "#f2f0e5" # overlay

active_tab.bg_color = "#fffcf0" # base
active_tab.fg_color = "#100f0f" # text

inactive_tab.bg_color = "#f2f0e5" # overlay
inactive_tab.fg_color = "#6f6e69" # subtle

inactive_tab_hover.bg_color = "#fffdf5" # surface
inactive_tab_hover.fg_color = "#100f0f" # text

new_tab.bg_color = "#f2f0e5" # overlay
new_tab.fg_color = "#6f6e69" # subtle

new_tab_hover.bg_color = "#fffdf5" # surface
new_tab_hover.fg_color = "#100f0f" # text
new_tab.fg_color = "#6f6e69" # subtle

new_tab_hover.bg_color = "#fffdf5" # surface
new_tab_hover.fg_color = "#100f0f" # text
